### ISSUE TITLE
Tag 4 scp not tagging the path

### ISSUE THREAD

**Issue by iPieceOfCake** [jhook777/5hell-for-Grey-Hack-the-Game#8]
Hello Plu70,

I just started using your tool, thank you very very much, having so much fun learning it and Grey Hack. I have noticed something that either I am doing something wrong or it is a bug. I have a file (pdf) on MALP that I wish to download using scp, when I select the file in MALP and click 4 (tag 4 scp) it ignores the path and just says Tagged: for scp. I was expecting to have Tagged: [path] for scp.
![Screenshot 2024-04-12 235358](https://github.com/jhook777/5hell-for-Grey-Hack-the-Game/assets/166891005/e1891f10-da4a-4de6-aa19-a73895ae60d8)

I saw a video from Michael Ray and it should look like this, Tagged: [path] for scp.:
![Screenshot 2024-04-12 235532](https://github.com/jhook777/5hell-for-Grey-Hack-the-Game/assets/166891005/3b0ca81a-abf1-4df8-84fa-a3162fbc9588)

Let me know. Thank you!

**Comment by iPieceOfCake** [comment]
All that to say when I use scpm, because the tag did not work, the path is empty.

**Comment by jhook777** [comment]
thanks for the report! found and fixed. V 3.7.7 and forward wont have this issue
